version: '3.8'
services:
  codecamp_db:
    image: postgres:14
    restart: always
    container_name: 'codecamp_db'
    environment:
      POSTGRES_PASSWORD: '1234'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'camp'
    #  POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 5433:5432
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
